### PR TITLE
Fixed missing char + added some more function documentation

### LINKED ISSUE #5: [BUG] Function call fails to pass first character
Thought it would be better to open an issue for this than use the OSI issue. 

I noticed the [Fixed the test_function_call test](https://github.com/mjarkk/general_programming_language/commit/57bc2399a3c10c6a4caed571ec952f62a7055e2f) commit and equalised my fork. 
After rerunning the tests, I edited example.gpl to include a function call. 
Now for some reason it would not accept any newlines inside the function. 
But the real issue is that after checking the console log, I noticed that the parsed `mpty` as ActionFunctionCall.name when the function I was calling was named `empty`. 

This was the console log outputted by main:
```
[Function { name: Some("empty"), args: [], body: Actions { list: [] } }, Function { name: Some("take_args"), args: [("a", Type { name: "int" }), ("b", Type { name: "int" })], body: Actions { list: [] } }, Function { name: Some("main"), args: [], body: Actions { list: [FunctionCall(ActionFunctionCall { name: "mpty", arguments: [] })] } }]
```

I also made the test log the output for further info, and got this:
```
running 1 test
Parser { index: 72, contents: [10, 32, 32, 32, 32, 32, 32, 102, 110, 32, 116, 101, 115, 116, 40, 41, 32, 123, 10, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 102, 110, 32, 109, 97, 105, 110, 40, 41, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 116, 101, 115, 116, 40, 41, 10, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 
32, 32], functions: [Function { name: Some("test"), args: [], body: Actions { list: [] } }, Function { name: Some("main"), args: [], body: Actions { list: [FunctionCall(ActionFunctionCall { name: "est", arguments: [] })] } }] }
```

My modified test looks like this:
```
#[test]
fn test_function_call_without_args() {
  let res = parse_str(
    r#"
      fn test() {
      }
      fn main() {
        test()
      }
    "#,
  );
  println!("{:?}", res);
}
```

My modified example.gpl
```
fn empty() {}

fn take_args(a int, b int) {}

fn main() { empty() }
```

### PR DESCRIPTION
**Pull request by TheOtterlord**
- Fixes #5
- Adds some more function docs
- Adds a function call to example file

### CODE REVIEW

File: src/lib/parser.rs [hunk 1]
```diff
@@ -150,7 +150,7 @@ impl Parser {
       }
     }
 
-    let mut char_count: usize = 0;
+    let mut char_count: usize = 1;
```
Comment (mjarkk) [inline src/lib/parser.rs]: This won't work because a few lines after here we do `match option.as_bytes().get(char_count) {` and that will return invalid relative characters.  
below the `while` we can better do:
```
self.index -= char_count + 1;
```

File: src/example.gpl [hunk 2]
```diff
@@ -1,3 +1,5 @@
 fn empty() {}
 
 fn take_args(a int, b int) {}
+
+fn main() { empty() }
```
Comment (mjarkk) [inline src/example.gpl:5]: Maybe we should add this file to the .gitignore so we can freely test code

**Review by mjarkk — CHANGES_REQUESTED** [review]
Found a few small issues

File: src/lib/parser.rs (hunk 1 above)
Comment (theotterlord) [reply src/lib/parser.rs]: Ah, this is much better. I'll make the changes now

File: src/example.gpl (hunk 2 above)
Comment (theotterlord) [reply src/example.gpl:5]: Yeah, this would make things much easier. 
Since we now have some documentation and a roadmap, this file is not needed for the original purposes.

Comment (theotterlord) [reply src/example.gpl:5]: I've added a filter for all gpl files in src. This will help when we need to test multi-file features

Comment (theotterlord) [reply src/example.gpl:5]: I've added a filter for all gpl files in src. This will help when we need to test multi-file features

**Comment by mjarkk** [comment]
Great! i'll merge the pr

**Comment by mjarkk** [comment]
maybe something next could be adding support for comments.  
I thought they would just be something like `//` for 1 line comments and `/* */` for multi line comments

**Comment by theotterlord** [comment]
Yeah, most languages use this syntax so it will help people migrate over. It also allows us to start documenting our tests & examples.

**Comment by mjarkk** [comment]
I think this could be best implemented in the `next_char` function because this needs to be everywhere possible.  
Although if we ever want to support code .gpl file formatting we might want to remember some comment context but we can always add that later.

**Comment by theotterlord** [comment]
For now, best to just implement the ability to use comments. And yes, I think that `next_char` is a good place to put it.
